=== Nev433/rail-projects/standards/railML/3.3/source/codelists/InfrastructureManagers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2022 rel. 2 (x64) (http://www.altova.com) by  (railML.org) -->
<xs:schema
  xmlns:railcode="https://www.railml.org/schemas/lists"
  xmlns:xml="http://www.w3.org/XML/1998/namespace"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://www.railml.org/schemas/lists"
  elementFormDefault="qualified"
  version="1.0">
  <xs:annotation>
    <xs:documentation>Copyright (c) railML.org e.V. Dresden/Germany; All Rights Reserved.</xs:documentation>
    <xs:documentation>This work is licensed under the restricted CreativeCommons Attribution-NonCommercial-NoDerivatives 4.0 International License with additional license conditions of railML.org.</xs:documentation>
    <xs:documentation>For further information see: https://www.railml.org/licence</xs:documentation>
    <xs:documentation>Content of this file: XML Schema for railML(R) (Definition of data types for the infrastructure manager code list)</xs:documentation>
  </xs:annotation>
  <xs:include schemaLocation="ListBaseTypes.xsd"/>
  <xs:element name="infrastructureManagerCodes">
    <xs:annotation>
      <xs:documentation>Container/Root element for "infrastructure manager codes"</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="infrastructureManager" type="railcode:tInfrastructureManager" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>Single entries for each infrastructure manager</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="tInfrastructureManager">
    <xs:sequence>
      <xs:element name="name" type="railcode:tI18NString" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Internationalized name of the infrastructure manager</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="validity" type="railcode:tValidity" minOccurs="0">
        <xs:annotation>
          <xs:documentation>If necessary, put time validity constraints here</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="isoCountryCode" type="railcode:tIsoCountryCode" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Two alpha ISO country code according to ISO 3166-1</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="companyCode" type="railcode:tCompanyCode" minOccurs="0">
        <xs:annotation>
          <xs:documentation>company codes according TAF TAP TSI B.8 or UIC IRS/leaflet 920-1:2006</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="code" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>code, that should be referred to from within a railML file, typically a short name for the infrastructure manager in Latin letters</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="tValidity">
    <xs:attribute name="begin" type="xs:date">
      <xs:annotation>
        <xs:documentation>Start date of validity</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="end" type="xs:date">
      <xs:annotation>
        <xs:documentation>End date of validity</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:simpleType name="tIsoCountryCode">
    <xs:restriction base="xs:string">
      <xs:length value="2"/>
      <xs:pattern value="[A-Z]{2}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="tCompanyCode">
    <xs:restriction base="xs:string">
      <xs:length value="4"/>
      <xs:pattern value="[0-9A-Z]{4}"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Nev433/rail-projects/standards/railML/3.3/source/codelists/InfrastructureManagers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) railML.org e.V. Dresden/Germany; All Rights Reserved.
     This work is licensed under the restricted CreativeCommons Attribution-NonCommercial-NoDerivatives 4.0 International License with additional license conditions of railML.org.
     For further information see: https://www.railml.org/licence
     Content of this file: XML Code List for railML(R) Definition of infrastructure manager codes, mostly used by infrastructure sub schema (IS) -->
<infrastructureManagerCodes xmlns="https://www.railml.org/schemas/lists" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.railml.org/schemas/lists InfrastructureManagers.xsd">
  <infrastructureManager code="ADIF">
    <name xml:lang="es">Administrador de Infraestructuras Ferroviarias (ADIF)</name>
    <name xml:lang="en">Administrator of Railway Network</name>
    <isoCountryCode>ES</isoCountryCode>
    <companyCode>0071</companyCode>
  </infrastructureManager>
  <infrastructureManager code="ARTC">
    <name xml:lang="en">Australian Rail Track Corporation</name>
    <validity begin="1998-07-01"/>
    <isoCountryCode>AU</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="AVG">
    <name xml:lang="de">Albtal-Verkehrs-Gesellschaft mbH</name>
    <isoCountryCode>DE</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="BC">
    <name xml:lang="en">Belarusian Railways</name>
    <isoCountryCode>BY</isoCountryCode>
    <companyCode>0021</companyCode>
  </infrastructureManager>
  <infrastructureManager code="BDK">
    <name xml:lang="dk">Banedanmark</name>
    <isoCountryCode>DK</isoCountryCode>
    <companyCode>0086</companyCode>
  </infrastructureManager>
  <infrastructureManager code="BLS">
    <name xml:lang="de">BLS Netz</name>
    <isoCountryCode>CH</isoCountryCode>
    <companyCode>0063</companyCode>
  </infrastructureManager>
  <infrastructureManager code="BN">
    <name>Bane NOR SF</name>
    <validity begin="2017-01-01"/>
    <isoCountryCode>NO</isoCountryCode>
    <companyCode>0076</companyCode>
  </infrastructureManager>
  <infrastructureManager code="BRE">
    <name xml:lang="de">Bayerische Regionaleisenbahn</name>
    <isoCountryCode>DE</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="CFL">
    <name>Société Nationale des Chemins de Fer Luxembourgeois</name>
    <isoCountryCode>LU</isoCountryCode>
    <companyCode>0082</companyCode>
  </infrastructureManager>
  <infrastructureManager code="CFM">
    <name>Calea Ferată din Moldova</name>
    <isoCountryCode>MD</isoCountryCode>
    <companyCode>0023</companyCode>
  </infrastructureManager>
  <infrastructureManager code="CFR">
    <name>Societatea Naţională de Transport Feroviar de Călători</name>
    <isoCountryCode>RO</isoCountryCode>
    <companyCode>1153</companyCode>
  </infrastructureManager>
  <infrastructureManager code="CIE">
    <name>Córas Iompair Éireann</name>
    <isoCountryCode>IE</isoCountryCode>
    <companyCode>0060</companyCode>
  </infrastructureManager>
  <infrastructureManager code="DBN">
    <name xml:lang="de">DB Netz AG</name>
    <validity end="2023-01-27"/>
    <isoCountryCode>DE</isoCountryCode>
    <companyCode>0080</companyCode>
  </infrastructureManager>
  <infrastructureManager code="DB Netz AG">
    <name xml:lang="de">DB Netz AG</name>
    <validity begin="2023-01-28"/>
    <isoCountryCode>DE</isoCountryCode>
    <companyCode>0080</companyCode>
  </infrastructureManager>
  <infrastructureManager code="DRE">
    <name xml:lang="de">Deutsche Regionaleisenbahn</name>
    <isoCountryCode>DE</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="EDS">
    <name>ΕΔΙΣΥ</name>
    <isoCountryCode>GR</isoCountryCode>
    <companyCode>0073</companyCode>
  </infrastructureManager>
  <infrastructureManager code="evb">
    <name xml:lang="de">Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH</name>
    <validity end="2023-01-27"/>
    <isoCountryCode>DE</isoCountryCode>
    <companyCode>3440</companyCode>
  </infrastructureManager>
  <infrastructureManager code="evb Infrastruktur">
    <name xml:lang="de">Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH</name>
    <validity begin="2023-01-28"/>
    <isoCountryCode>DE</isoCountryCode>
    <companyCode>3440</companyCode>
  </infrastructureManager>
  <infrastructureManager code="EVR">
    <name>EVR</name>
    <isoCountryCode>EE</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="FTA">
    <name xml:lang="fi">Liikennevirasto Helsinki, Finland</name>
    <name xml:lang="en">Finish Transport Agency</name>
    <isoCountryCode>FI</isoCountryCode>
    <companyCode>3109</companyCode>
  </infrastructureManager>
  <infrastructureManager code="GET">
    <name xml:lang="en">Getlink</name>
    <isoCountryCode>FR</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="GKB">
    <name xml:lang="de">Graz-Köflacher Bahn und Busbetrieb GmbH</name>
    <isoCountryCode>AT</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="GyS">
    <name>GySEV</name>
    <isoCountryCode>HU</isoCountryCode>
    <companyCode>0043</companyCode>
  </infrastructureManager>
  <infrastructureManager code="HS2">
    <name xml:lang="en">High Speed Two Ltd.</name>
    <isoCountryCode>UK</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="HSB">
    <name xml:lang="de">Harzer Schmalspurbahnen GmbH</name>
    <isoCountryCode>DE</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="HZI">
    <name>HŽ Infrastruktura</name>
    <isoCountryCode>HR</isoCountryCode>
    <companyCode>0078</companyCode>
  </infrastructureManager>
  <infrastructureManager code="HzL">
    <name xml:lang="de">Hohenzollerische Landesbahn AG</name>
    <isoCountryCode>DE</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="InB">
    <name>Infrabel</name>
    <isoCountryCode>BE</isoCountryCode>
    <companyCode>0088</companyCode>
  </infrastructureManager>
  <infrastructureManager code="ISR">
    <name xml:lang="he">רַכֶּבֶת יִשְׂרָאֵל</name>
    <name xml:lang="en">Israel Railways</name>
    <isoCountryCode>IL</isoCountryCode>
    <companyCode>0095</companyCode>
  </infrastructureManager>
  <infrastructureManager code="JBV">
    <name>Jernbaneverket</name>
    <validity end="2016-12-31"/>
    <isoCountryCode>NO</isoCountryCode>
    <companyCode>0076</companyCode>
  </infrastructureManager>
  <infrastructureManager code="KTMB">
    <name xml:lang="ms">Keretapi Tanah Melayu</name>
    <isoCountryCode>MY</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="KZH">
    <name>Kazakhstan Temir Zholy</name>
    <isoCountryCode>KZ</isoCountryCode>
    <companyCode>0027</companyCode>
  </infrastructureManager>
  <infrastructureManager code="LDz">
    <name>Latvijas dzelzceļš</name>
    <isoCountryCode>LV</isoCountryCode>
    <companyCode>0025</companyCode>
  </infrastructureManager>
  <infrastructureManager code="LG">
    <name>AB 'Lietuvos geležinkeliai'</name>
    <isoCountryCode>LT</isoCountryCode>
    <companyCode>0024</companyCode>
  </infrastructureManager>
  <infrastructureManager code="MGB">
    <name>Matterhorn Gotthard Bahn</name>
    <isoCountryCode>CH</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="MZ">
    <name>Makedonski Železnici Infrastructure-Skopje</name>
    <isoCountryCode>MK</isoCountryCode>
    <companyCode>0065</companyCode>
  </infrastructureManager>
  <infrastructureManager code="NEB">
    <name>Niederbarnimer Eisenbahn AG, Berlin</name>
    <isoCountryCode>DE</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="NR">
    <name>Network Rail Limited</name>
    <isoCountryCode>GB</isoCountryCode>
    <companyCode>0070</companyCode>
  </infrastructureManager>
  <infrastructureManager code="NKS">
    <name>National Railway Infrastructure Company</name>
    <isoCountryCode>BG</isoCountryCode>
    <companyCode>0052</companyCode>
  </infrastructureManager>
  <infrastructureManager code="ÖBB">
    <name>ÖBB Infra</name>
    <isoCountryCode>AT</isoCountryCode>
    <companyCode>0081</companyCode>
  </infrastructureManager>
  <infrastructureManager code="OHE">
    <name>Osthannoversche Eisenbahnen AG</name>
    <isoCountryCode>DE</isoCountryCode>
  </infrastructureManager>
  <infrastructureManager code="OSE">
    <name xml:lang="gr">Οργανισμός Σιδηροδρόμων Ελλάδος</name>
    <name xml:lang="en">Hellenic Railways Organisation, Athen</name>
    <isoCountryCode>GR</isoCountryCode>
    <companyCode>0073</companyCode>
  </infrastructureManager>
  <infrastructureManager code="PLK">
    <name>PKP Polskie Linie Kolejowe S.A.</name>
    <isoCountryCode>PL</isoCountryCode>
    <companyCode>0051</companyCode>
  </infrastructureManager>
  <infrastructureManager code="PrR">
    <name>ProRail</name>
    <isoCountryCode>NL</isoCountryCode>
    <companyCode>0084</companyCode>
  </infrastructureManager>
  <infrastructureManager code="REF">
    <name>Infraestruturas de Portugal S.A.</name>
    <isoCountryCode>PT</isoCountryCode>
    <companyCode>0094</companyCode>
  </infrastructureManager>
  <infrastructureManager code="RFF">
    <name>SNCF Réseau</name>
    <isoCountryCode>FR</isoCountryCode>
    <companyCode>0087</companyCode>
  </infrastructureManager>
  <infrastructureManager code="RFI">
    <name>Ferrovie dello Stato Italiane SpA</name>
    <isoCountryCode>IT</isoCountryCode>
    <companyCode>0083</companyCode>
  </infrastructureManager>
  <infrastructureManager code="RhB">
    <name>Rhätische Bahn AG</name>
    <isoCountryCode>CH</isoCountryCode>
    <companyCode>3267</companyCode>
  </infrastructureManager>
